FROM php:8.3-cli

RUN apt-get update && apt-get install -y \
    git unzip curl zip libpq-dev \
    nodejs npm \
    && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . .

RUN composer install --no-dev --optimize-autoloader --no-scripts

RUN npm install
RUN npm run build

EXPOSE 10000

# CMD php artisan optimize:clear && \
#     php artisan migrate --force && \
#     php artisan db:seed --force && \
#     php artisan serve --host=0.0.0.0 --port=$PORT

# CMD php artisan optimize:clear && \
#     php artisan storage:link && \
#     php artisan migrate:fresh --seed --force && \
#     php artisan serve --host=0.0.0.0 --port=$PORT

CMD php artisan optimize:clear && \
    php artisan migrate:fresh --force && \
    php artisan serve --host=0.0.0.0 --port=$PORT